# Generated by Django 5.2.15 on 2026-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=25)),
                ('vehicle_number', models.CharField(max_length=25)),
                ('owner_name', models.CharField(max_length=50)),
                ('parked_hours', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('Parked', 'Parked'), ('Free', 'Free')], default='Free', max_length=25)),
            ],
        ),
    ]
